deployment:
  svc: true
  bff: true
  ui: true

product:
  info:
    data:
      description: "DB Concessions"
      imageUrl: ""
      iconName: "lock"
      displayName: "DB Concessions"
      basePath: "/concessions"
      
